# columns:
#   [セクション名]:
#     name: 項目列名。
#     md_pattern: 正規表現。必ずシングルクォートで囲むこと。
#     length: セルの幅。
#     horizontal: セル内の文字の水平位置。center, left, right
#     vertical: セル内の文字の垂直位置。center, top, bottom
#     multi-idx: 複数のインデックスを持つかどうか。true, false
columns:
    number:
        name: "No."
        length: 6
        horizontal: "center"
        vertical: "center"
    section:
        name: "大項目"
        md_pattern: "^# (.+)$"
        length: 30
        horizontal: "left"
        vertical: "top"
        multi-idx: true
    subsection:
        name: "中項目"
        md_pattern: "^## (.+)$"
        length: 30
        horizontal: "left"
        vertical: "top"
        multi-idx: true
    testcase:
        name: "小項目"
        md_pattern: "^### (正常|異常|準正常) (OK|NG|NA|--|未|未実施) (.+)$"
        length: 30
        horizontal: "left"
        vertical: "top"
        multi-idx: true
    pos-neg:
        name: "系" # 改行したい場合はダブルクォーテーションで囲む
        length: 10
        horizontal: "center"
        vertical: "center"
    step:
        name: "手順"
        md_pattern: '^\- (.+)$'
        length: 70
        horizontal: "left"
        vertical: "top"
    expectation:
        name: "期待値"
        md_pattern: '^\+ (.+)$'
        length: 70
        horizontal: "left"
        vertical: "top"
    notes:
        name: "前提"
        md_pattern: '^\* (.+)$'
        length: 40
        horizontal: "left"
        vertical: "top"
    conduction_date:
        name: "実施日"
        md_pattern: ""
        length: 10
        horizontal: "center"
        vertical: "center"
    conductor:
        name: "実施者"
        md_pattern: ""
        length: 10
        horizontal: "center"
        vertical: "center"
    result:
        name: "結果"
        length: 10
        horizontal: "center"
        vertical: "center"
    check_date:
        name: "確認日"
        md_pattern: ""
        length: 10
        horizontal: "center"
        vertical: "center"
    checker:
        name: "確認者"
        md_pattern: ""
        length: 10
        horizontal: "center"
        vertical: "center"
    bikou:
        name: "備考"
        md_pattern: "^/ (.+)$"
        length: 20
        horizontal: "center"
        vertical: "center"

excel_settings:
    # font_name: Meiryo UI
    font_name: YuGothic
    sheet_name:
        summary: 概要
        test: 単体試験項目書
